// Listado curado de consultoras/software factories/staffing con foco o
// práctica de QA (manual & automation) en Argentina. Es un directorio de
// referencia para outreach, no un feed en vivo: no se scrapea ninguna fuente,
// las URLs son las que se verificaron al armar el listado.
export const CONSULTORAS = [
  { id: 'vates', name: 'Vates', category: 'Especializada en QA', city: 'Buenos Aires', note: 'Más de 30 años en testing, QA automation y certificación de software crítico', link: '' },
  { id: 'a1qa', name: 'a1qa (Argentina)', category: 'Especializada en QA', city: 'CABA', note: 'QA para fintech, banca, telecom y gaming', link: 'https://a1qa.ar/' },
  { id: 'qualis-lab', name: 'Qualis Lab', category: 'Especializada en QA', city: 'CABA', note: 'Automation, stress test, mobile testing, UX/vulnerability testing', link: 'https://www.qualis-lab.com/' },
  { id: 'bairesqa', name: 'BairesQA', category: 'Especializada en QA', city: 'Vicente López', note: 'QA de apps web y mobile, alta exposición a terceros', link: 'https://clutch.co/profile/bairesqa' },
  { id: 'gbsys', name: 'GBSYS', category: 'Especializada en QA', city: 'Argentina', note: 'QA y testing: unitarias, integrales, performance', link: 'https://www.gbsys.com/servicios/qa-testing/' },
  { id: 'tester-smart', name: 'Tester Smart', category: 'Especializada en QA', city: 'Puerto Madero, CABA', note: 'Consultoría gerencial y capacitación ISTQB en testing', link: 'https://tester.com.ar/' },
  { id: 'crowdar', name: 'CrowdAr', category: 'Especializada en QA', city: 'Buenos Aires', note: 'Testing manual y automatizado, muy bien puntuada en Clutch', link: 'https://clutch.co/profile/crowdar' },
  { id: 'arbusta', name: 'Arbusta', category: 'Especializada en QA', city: 'CABA', note: 'QA manual, empresa con enfoque de inclusión laboral', link: 'https://clutch.co/profile/arbusta' },
  { id: 'nahual-it', name: 'Nahual IT', category: 'Especializada en QA', city: 'Buenos Aires', note: 'Testing con foco también en accesibilidad digital', link: 'https://clutch.co/profile/nahual-it' },
  { id: 'hichex', name: 'hiChex', category: 'Especializada en QA', city: 'Córdoba', note: 'Staffing especializado en recursos de QA', link: 'https://clutch.co/profile/hichex' },
  { id: 'qalified', name: 'QAlified', category: 'Especializada en QA', city: 'Uruguay (con proyectos AR)', note: 'Testing de software, muy bien rankeada', link: 'https://clutch.co/profile/qalified-0' },
  { id: 'betterqa', name: 'BetterQA', category: 'Especializada en QA', city: 'Internacional (atiende AR)', note: 'App testing y QA end-to-end', link: 'https://clutch.co/profile/betterqa' },

  { id: 'baufest', name: 'Baufest', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'QA junto a DevOps y ciberseguridad', link: 'https://developargentina.com/directorio/baufest' },
  { id: 'santex', name: 'Santex', category: 'Consultora IT con área QA', city: 'Córdoba / Buenos Aires', note: 'Desarrollo + QA, +26 años de trayectoria', link: 'https://developargentina.com/directorio/santex' },
  { id: 'snoop-consulting', name: 'Snoop Consulting', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Mobile, QA; clientes como Mercado Libre y Hospital Italiano', link: 'https://developargentina.com/directorio/snoop-consulting' },
  { id: 'grit', name: 'GRIT Tecnología y Soporte', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Infraestructura IT y soporte, incluye QA', link: 'https://developargentina.com/directorio/grit-tecnologia-y-soporte' },
  { id: 'epidata', name: 'Epidata', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Innovation outsourcing, partner de Salesforce/AWS', link: 'https://developargentina.com/directorio/epidata' },
  { id: 'practia', name: 'Practia Argentina', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Práctica dedicada a QA, Testing y Calidad Técnica', link: 'https://argentina.practia.global/servicios/qa-testing-calidad-tecnica/' },
  { id: 'huenei', name: 'Huenei IT Services', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: '+25 años, testing como parte de su portfolio', link: 'https://clutch.co/profile/huenei-it-services' },
  { id: 'xoor', name: 'XOOR Inc.', category: 'Consultora IT con área QA', city: 'Mar del Plata', note: 'Staff augmentation, incluye QA', link: 'https://clutch.co/profile/xoor' },
  { id: 'cumbresoft', name: 'CUMBRESOFT Argentina', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Desarrollo + testing para sector público/educativo', link: 'https://clutch.co/profile/cumbresoft-argentina' },
  { id: 'velocity-partners', name: 'Velocity Partners (Endava)', category: 'Consultora IT con área QA', city: 'Rosario', note: 'QA dentro de su práctica .NET', link: 'https://clutch.co/profile/velocity-partners' },
  { id: 'hexacta', name: 'Hexacta (hoy GlobalLogic)', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Testing e ingeniería de datos', link: 'https://clutch.co/profile/hexacta' },
  { id: 'outside-the-box', name: 'Outside the Box', category: 'Consultora IT con área QA', city: 'Córdoba', note: 'QA + staff augmentation', link: 'https://clutch.co/profile/outside-box-0' },
  { id: 'mobeats', name: 'Mobeats', category: 'Consultora IT con área QA', city: 'Berazategui', note: 'Equipos dedicados a testing en sus proyectos', link: 'https://clutch.co/profile/mobeats' },
  { id: 'neps', name: 'NEPS', category: 'Consultora IT con área QA', city: 'Anisacate, Córdoba', note: 'QA como parte de refactors y desarrollo', link: 'https://clutch.co/profile/neps' },
  { id: 'southern-minds', name: 'Southern Minds', category: 'Consultora IT con área QA', city: 'Rosario', note: 'Testing dentro de sus equipos de producto', link: 'https://clutch.co/profile/southern-minds' },
  { id: 'newbitcrew', name: 'NewBitCrew', category: 'Consultora IT con área QA', city: 'CABA', note: 'Asignan testers dedicados en sus proyectos', link: 'https://clutch.co/profile/newbitcrew' },
  { id: 'kambrica', name: 'Kambrica', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Consultora de producto con testing incluido', link: 'https://clutch.co/profile/kambrica' },
  { id: 'distillery', name: 'Distillery', category: 'Consultora IT con área QA', city: 'Mendoza (HQ California)', note: 'QA testing nearshore, fintech/salud', link: '' },
  { id: 'bairesdev', name: 'BairesDev', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'Staff augmentation con perfiles QA', link: 'https://clutch.co/profile/bairesdev' },
  { id: 'intive', name: 'intive (ex Hexacta/Belatrix)', category: 'Consultora IT con área QA', city: 'Buenos Aires', note: 'QA como parte de su oferta de ingeniería', link: '' },
  { id: 'nanlabs', name: 'NaNLABS', category: 'Consultora IT con área QA', city: 'La Plata', note: 'Boutique técnica, cloud/data con QA', link: '' },

  { id: 'globant', name: 'Globant', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'QA/testing como parte de su ingeniería digital', link: '' },
  { id: 'accenture-ar', name: 'Accenture Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Incluye Wolox (ex startup argentina adquirida)', link: '' },
  { id: 'ibm-ar', name: 'IBM Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Consultoría + QA en proyectos grandes', link: '' },
  { id: 'capgemini-ar', name: 'Capgemini Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: '' },
  { id: 'cognizant-ar', name: 'Cognizant Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: '' },
  { id: 'nttdata-ar', name: 'NTT DATA Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: '' },
  { id: 'tcs-ar', name: 'TCS (Tata Consultancy) Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: '' },
  { id: 'softtek-ar', name: 'Softtek Argentina', category: 'Multinacional con oficina AR', city: 'La Plata', note: 'Centro Global de Entrega en La Plata', link: 'https://www.softtek.com/es/nuestra-compa%C3%B1ia' },
  { id: 'sonda-ar', name: 'Sonda Argentina', category: 'Multinacional con oficina AR', city: 'CABA', note: '', link: '' },
  { id: 'endava-ar', name: 'Endava Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: 'Incluye Velocity Partners (Rosario)', link: '' },
  { id: 'neoris-epam', name: 'Neoris / EPAM Argentina', category: 'Multinacional con oficina AR', city: 'Santa Fe', note: 'Neoris se integró a EPAM en 2024', link: '' },
  { id: 'dxc-ar', name: 'DXC Technology Argentina', category: 'Multinacional con oficina AR', city: 'Buenos Aires', note: '', link: '' },

  { id: 'randstad-tech', name: 'Randstad Technologies Argentina', category: 'Staffing / recruiting IT', city: 'CABA', note: 'División IT dedicada, incluye QA', link: 'https://www.randstad.com.ar/empresas/areas-de-expertise/it/' },
  { id: 'adecco-ar', name: 'Grupo Adecco Argentina (IT)', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: '', link: '' },
  { id: 'manpower-ar', name: 'ManpowerGroup / Experis Argentina', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: '', link: '' },
  { id: 'sionix', name: 'Sionix', category: 'Staffing / recruiting IT', city: 'Godoy Cruz, Mendoza', note: 'Recruiting técnico especializado', link: 'https://clutch.co/profile/sionix' },
  { id: 'grupo-assa', name: 'Grupo Assa', category: 'Staffing / recruiting IT', city: 'Buenos Aires', note: 'Consultora de RRHH/IT con selección de perfiles QA', link: '' },
];
