// Ofertas relevadas a mano (bolsas propias de cada consultora: mail, portal
// propio, LinkedIn). No salen de las fuentes remotas escaneadas; se agregan
// manualmente a su país (región). Cada entrada incluye el texto de la vacante
// con sus skills para que el motor de matching calcule el % correctamente.
export const CURATED_JOBS = [
  // ============ ARGENTINA ============
  {
    id: 'curated-crowdar-qa',
    source: 'Directo (Crowdar)',
    title: 'QA / QA Automation Engineer',
    company: 'Crowdar',
    location: 'Buenos Aires, Argentina',
    regionGuess: 'argentina',
    applyUrl: 'https://crowdar.peopleforce.io/careers',
    description:
      'Crowdar (organizadora de Testear.la) suma perfiles de QA y Testing: QA Automation, Tester Manual, Chapter Lead, y roles en automatización, desarrollo, data, cloud y SAP. Valoramos experiencia en testing funcional y automatizado (web y mobile), APIs, y conocimiento de metodologías ágiles. Suma el uso de IA aplicada a testing y automatización inteligente.',
    tags: ['qa', 'qa automation', 'testing', 'automation', 'manual testing', 'api testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-qactions-sap',
    source: 'Directo (QActions)',
    title: 'QA Manager / Test Manager SAP',
    company: 'QActions',
    location: 'Buenos Aires, Argentina',
    regionGuess: 'argentina',
    applyUrl: 'https://qactions.com',
    description:
      'En QActions buscamos un perfil con experiencia comprobable en testing de implementaciones o upgrades SAP, para liderar estrategias, equipos y planes de prueba hasta el go-live. Valoramos experiencia como QA Lead, Test Lead SAP, Testing Manager o Líder de Testing y contacto con clientes. Excluyente Buenos Aires, modalidad híbrida. Postulación por mail a busquedas@qactions.com.',
    tags: ['qa', 'testing', 'sap', 'test lead', 'test manager', 'agile'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-cocos-qa',
    source: 'Directo (Cocos Capital)',
    title: 'Senior QA Engineer',
    company: 'Cocos Capital',
    location: 'Buenos Aires, Argentina',
    regionGuess: 'argentina',
    applyUrl: 'https://cocoscapital.recruitee.com/o/senior-qa-engineer',
    description:
      'Cocos Capital, fintech argentina de inversión y cripto, busca Senior QA Engineer (híbrido, Buenos Aires). Buscamos experiencia en productos digitales, idealmente fintech, banca, pagos o cripto. Suma contar con background en desarrollo de software, usar herramientas de IA aplicadas a testing (GitHub Copilot, agentic QA tools, generación de test cases con LLMs) y experiencia en testing de seguridad.',
    tags: ['qa', 'senior qa', 'testing', 'fintech', 'automation', 'api testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-ar-fx-analista-funcional',
    source: 'Directo (FX Informática)',
    title: 'Analista Funcional',
    company: 'FX Informática',
    location: 'Argentina (Remoto)',
    regionGuess: 'argentina',
    applyUrl: 'https://www.fxinformatica.com',
    description:
      'FX Informática busca Analistas Funcionales para proyectos internos y externos: relevamiento de requerimientos, testing, soporte y capacitación a usuarios, documentación y demostraciones de productos. Orientado a estudiantes o graduados de Administración, Comercio Internacional, Sistemas o afines. Valoramos capacidad de análisis, trabajo en equipo, comunicación, gestión de proyectos, manejo de Jira y SQL, inglés y/o portugués. Remoto lunes a viernes 9-18hs. Enviar CV a rrhh@fxinformatica.com.',
    tags: ['qa', 'analista funcional', 'analista', 'testing', 'jira', 'sql', 'functional testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-ar-fx-desarrollador',
    source: 'Directo (FX Informática)',
    title: 'Desarrollador (células de desarrollo)',
    company: 'FX Informática',
    location: 'Argentina (Remoto)',
    regionGuess: 'argentina',
    applyUrl: 'https://www.fxinformatica.com',
    description:
      'FX Informática busca desarrolladores para células de desarrollo: diseño, desarrollo, configuración y entrega de soluciones de software. Conocimientos en .NET Core / C#, SQL Server, HTML5, CSS y JavaScript. Se valoran Git/TFS, DevOps, Azure, Oracle y metodologías ágiles. Remoto lunes a viernes 9-18hs. Enviar CV a rrhh@fxinformatica.com.',
    tags: ['quality', 'test', 'javascript', 'sql', 'agile', 'azure devops', 'ci/cd'],
    salary: '',
    date: '2026-09-01',
  },

  // ============ MÉXICO ============
  {
    id: 'curated-mx-coderdoad-qa-auto',
    source: 'Tech Jobs in Mexico',
    title: 'QA Automation Engineer',
    company: 'CodeRoad Inc',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/ez9E4ydp',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA Automation Engineer en CodeRoad Inc, modalidad 100% remota para todo el país. Automatización de pruebas, testing funcional y de regresión, APIs y metodologías ágiles.',
    tags: ['qa automation', 'automation', 'testing', 'api testing', 'agile'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-coderdoad-qa-manual',
    source: 'Tech Jobs in Mexico',
    title: 'Sr. QA Manual Engineer',
    company: 'CodeRoad Inc',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/e6TzVEJ7',
    description:
      'Búsqueda en Tech Jobs in Mexico: Sr. QA Manual Engineer en CodeRoad Inc, modalidad 100% remota. Pruebas funcionales, manuales y de regresión con foco en calidad de software.',
    tags: ['qa', 'manual testing', 'testing', 'functional testing', 'regression'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-rapptr-qa-analyst',
    source: 'Tech Jobs in Mexico',
    title: 'QA Analyst',
    company: 'Rapptr Labs',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/da-MPwxD',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA Analyst en Rapptr Labs, modalidad 100% remota. Análisis y ejecución de pruebas funcionales, test cases y reporte de defectos en entornos ágiles.',
    tags: ['qa', 'testing', 'functional testing', 'test cases', 'agile'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-devlane-sr-qa',
    source: 'Tech Jobs in Mexico',
    title: 'Sr. QA Engineer',
    company: 'Devlane',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/eK27UxgU',
    description:
      'Búsqueda en Tech Jobs in Mexico: Sr. QA Engineer en Devlane, modalidad 100% remota. Liderar estrategias de testing manual y automatizado, APIs, web y mobile en equipos ágiles.',
    tags: ['qa', 'senior qa', 'testing', 'automation', 'api testing', 'mobile testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-gila-sdet',
    source: 'Tech Jobs in Mexico',
    title: 'QA/SDET Engineer',
    company: 'Gila Software',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/ebSZhGAt',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA/SDET Engineer en Gila Software, modalidad 100% remota. Automatización de pruebas, diseño de frameworks de testing, APIs y CI/CD.',
    tags: ['qa', 'sdet', 'automation', 'test automation', 'api testing', 'ci/cd'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-nexaminds-qa-auto',
    source: 'Tech Jobs in Mexico',
    title: 'QA Automation Engineer',
    company: 'Nexaminds',
    location: 'México (100% Remoto)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/e_qX8HQY',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA Automation Engineer en Nexaminds, modalidad 100% remota. Automatización de pruebas web, mobile y APIs con foco en calidad.',
    tags: ['qa automation', 'automation', 'testing', 'mobile testing', 'api testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-globallogic-sr-auto',
    source: 'Tech Jobs in Mexico',
    title: 'Sr. Automation QA Engineer',
    company: 'GlobalLogic',
    location: 'CDMX, México (Híbrido)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/e22H2wyh',
    description:
      'Búsqueda en Tech Jobs in Mexico: Sr. Automation QA Engineer en GlobalLogic, modalidad híbrida en CDMX. Automatización de pruebas a gran escala, frameworks de testing, APIs y entornos ágiles.',
    tags: ['qa automation', 'automation', 'testing', 'api testing', 'agile'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-felix-sr-qa-auto',
    source: 'Tech Jobs in Mexico',
    title: 'Senior QA Automation Engineer',
    company: 'Félix',
    location: 'CDMX, México (Híbrido)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/gAeHh_Q6',
    description:
      'Búsqueda en Tech Jobs in Mexico: Senior QA Automation Engineer en Félix, modalidad híbrida en CDMX. Fintech de pagos; automatización de pruebas, APIs y servicios financieros.',
    tags: ['qa automation', 'automation', 'testing', 'api testing', 'fintech'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-verifone-qa-analyst',
    source: 'Tech Jobs in Mexico',
    title: 'Software QA Analyst',
    company: 'Verifone',
    location: 'CDMX, México (Híbrido)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/euZN3p8H',
    description:
      'Búsqueda en Tech Jobs in Mexico: Software QA Analyst en Verifone, modalidad híbrida en CDMX. Análisis y ejecución de pruebas funcionales y de regresión en productos de tecnología de pagos.',
    tags: ['qa', 'testing', 'functional testing', 'regression'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-mx-mtech-qa-tester',
    source: 'Tech Jobs in Mexico',
    title: 'QA Tester',
    company: 'MTech Systems',
    location: 'Querétaro, México (Híbrido)',
    regionGuess: 'mexico',
    applyUrl: 'https://lnkd.in/eBwRQ_U7',
    description:
      'Búsqueda en Tech Jobs in Mexico: QA Tester en MTech Systems, modalidad híbrida en Querétaro. Ejecución de pruebas manuales y funcionales, test cases y reporte de defectos.',
    tags: ['qa', 'tester', 'manual testing', 'functional testing', 'test cases'],
    salary: '',
    date: '2026-09-01',
  },

  // ============ PERÚ ============
  {
    id: 'curated-pe-valtx-qa-ia',
    source: 'Directo (Valtx)',
    title: 'QA Automatizador – IA',
    company: 'Valtx',
    location: 'Lima, Perú',
    regionGuess: 'peru',
    applyUrl: 'https://www.valtx.pe',
    description:
      'Valtx busca QA Automatizador – IA. Misión: diseñar e implementar una solución de QA potenciada por IA con agentes capaces de generar escenarios BDD, casos de prueba y scripts de automatización, integrándose con Jira/Rovo y usando Python, GitHub Copilot y modelos Claude. Tecnologías clave: Python, GitHub Copilot, modelos Claude, Jira/Rovo, BDD y automatización de pruebas, IA aplicada a QA. Postulación: enviar CV a lnunural@valtx.pe con nombre de posición y expectativas salariales.',
    tags: ['qa automation', 'automation', 'python', 'bdd', 'gherkin', 'jira', 'ai', 'ia'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-qds-qa-auto',
    source: 'Directo (QDS)',
    title: 'QA Automatizador',
    company: 'QDS - Quality & Development Software SAC',
    location: 'Lima, Perú (Híbrido)',
    regionGuess: 'peru',
    applyUrl: 'https://www.qds.com.pe',
    description:
      'QDS busca QA Automatizador (solo Perú, híbrido). Requisitos: Postman, Playwright y TypeScript, 3 años de experiencia en la posición, gestión de defectos (Jira/Azure DevOps), diseño de casos de prueba (Gherkin/BDD), pruebas funcionales, no funcionales y de regresión. Deseable: Performance Testing (JMeter) y conocimientos de OWASP. Enviar CV a eliana.santini@qds.com.pe.',
    tags: ['qa automation', 'automation', 'playwright', 'typescript', 'postman', 'api testing', 'bdd', 'gherkin', 'jira', 'azure devops', 'regression'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-interseguro-tpo',
    source: 'Directo (Interseguro)',
    title: 'Technical Product Owner',
    company: 'Interseguro Compañía de Seguros',
    location: 'Lima, Perú (Híbrido)',
    regionGuess: 'peru',
    applyUrl: 'https://l1nq.com/kb5gxw6',
    description:
      'Interseguro busca Technical Product Owner (solo Perú, híbrido). Bachiller o titulado en Ingeniería de Sistemas/Informática/Software. 3 a 5 años liderando equipos de desarrollo. Tecnologías: Angular, React, Vue, Nuxt, Java, .NET, Python, Golang, Node.js y SQL Server. Inglés intermedio deseable. Conocimientos de modelamiento de datos, virtualización y despliegue en Cloud, herramientas de IA Generativa (Cursor), Google Cloud Platform (Cloud Run, Cloud Storage, Cloud SQL, Cloud Functions, Pub/Sub), Kubernetes y CI/CD. Postular en el link.',
    tags: ['cloud', 'sql', 'python', 'agile', 'kubernetes', 'ci/cd', 'ai'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-coderslab-qa-ssr',
    source: 'Directo (CodersLab)',
    title: 'Especialista QA SSR',
    company: 'CodersLab',
    location: 'Lima, Perú (Híbrido)',
    regionGuess: 'peru',
    applyUrl: 'https://www.coderslab.io',
    description:
      'CodersLab busca Especialista QA SSR (Lima, Perú, híbrido). Mínimo 3 años ejecutando pruebas manuales de QA (excluyente). Certificación ISTQB Foundation Level o afines (excluyente). Consultas en bases de datos. Conocimientos o nociones de automatización. Ejecución y pruebas de servicios/APIs (Postman o similares). Ejecución de procesos ETL. Experiencia en sector bancario. Enviar CV a veronica.rueda@coderslab.io.',
    tags: ['qa', 'manual testing', 'testing', 'sql', 'api testing', 'postman', 'banking', 'istqb', 'etl'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-novacomp-sr-sdet',
    source: 'Directo (Novacomp)',
    title: 'Senior QA Automation / SDET',
    company: 'Novacomp',
    location: 'Lima, Perú (Híbrido)',
    regionGuess: 'peru',
    applyUrl: 'https://www.novacomp.com',
    description:
      'Novacomp busca Senior QA Automation / SDET (Lima, Perú, híbrido). Automatización enfocada en APIs (60-70%), Web (30%) y Mobile. Dominio de Playwright con TypeScript y herramientas como Karate o Selenium. Pruebas de rendimiento con K6. Enviar CV a fflores@crnova.com.',
    tags: ['qa automation', 'sdet', 'automation', 'api testing', 'playwright', 'typescript', 'selenium', 'mobile testing', 'performance testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-indra-qa-manager-uat',
    source: 'Directo (Indra)',
    title: 'QA Manager (UAT Banca)',
    company: 'Indra',
    location: 'San Isidro, Lima, Perú',
    regionGuess: 'peru',
    applyUrl: 'https://wa.link/ea14nb',
    description:
      'Indra busca QA Manager para liderar la estrategia y gestión de pruebas UAT en proyectos de alta criticidad del sector bancario. Requisitos: 8+ años en QA y 3+ años liderando equipos/servicios de pruebas; experiencia en QA/UAT, gestión de riesgos, integraciones, migraciones y Go/No-Go; experiencia indispensable en sector bancario; Jira/Xray o equivalentes; Ingeniería de Sistemas/Informática/Industrial. Deseable: ISTQB, PMP/PMI, Scrum/Agile y Bantotal. Presencial en San Isidro, Lima, lunes a viernes 9-18hs. Postulación: gmcaballerop@indracompany.com.',
    tags: ['qa', 'qa manager', 'uat', 'testing', 'banking', 'banca', 'jira', 'xray', 'agile', 'scrum', 'test cases'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-pe-nttd-bootcamp-qa',
    source: 'Directo (NTT DATA)',
    title: 'Bootcamp QA Automatizador',
    company: 'NTT DATA Europe & Latam',
    location: 'Perú (100% Remoto, provincias)',
    regionGuess: 'peru',
    applyUrl: 'https://lnkd.in/eZcd2R5T',
    description:
      'NTT DATA Europe & Latam busca profesionales para su Bootcamp QA Automation, convocatoria para profesionales que residan en provincias del Perú, modalidad 100% remota. Requisitos: 1 a 2 años de experiencia en QA Manual, experiencia en pruebas funcionales y reporte de incidencias, manejo de Jira y/o Postman (deseable), interés en desarrollarse en Automatización de Pruebas. Enviar CV a gbonillr@nttdata.com o postular en el anuncio.',
    tags: ['qa automation', 'qa', 'automation', 'manual testing', 'functional testing', 'jira', 'postman', 'api testing', 'test automation'],
    salary: '',
    date: '2026-09-01',
  },

  // ============ COLOMBIA ============
  {
    id: 'curated-co-ezertech-analista-qa',
    source: 'Directo (EZERTECH)',
    title: 'Analista QA',
    company: 'EZERTECH',
    location: 'Barranquilla, Colombia',
    regionGuess: 'colombia',
    applyUrl: 'https://www.ezertech.com.co',
    description:
      'EZERTECH busca Analista QA para software empresarial del sector salud (EPS). Mínimo 3 años en pruebas de software empresarial. Responsabilidades: diseñar planes, escenarios y casos de prueba; ejecutar pruebas funcionales, de integración y regresión; validaciones de datos; pruebas y validación de APIs; documentar y dar seguimiento a defectos; emitir concepto de calidad del release. Deseable: experiencia en sector salud/EPS/IPS/aseguramiento/facturación en salud, Postman para APIs, SQL básico para validación de datos, metodologías ágiles/Scrum, Jira, Azure DevOps o GitLab. Presencial en Barranquilla. Postulación por mail a soporte@ezertech.com.co.',
    tags: ['qa', 'analista qa', 'functional testing', 'manual testing', 'api testing', 'postman', 'sql', 'agile', 'scrum', 'jira', 'azure devops'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-co-qa-auto-ai-llm',
    source: 'Reclutador (LinkedIn)',
    title: 'QA Automation Engineer (AI / LLM)',
    company: 'Confidencial (Colombia)',
    location: 'Colombia',
    regionGuess: 'colombia',
    applyUrl: '',
    description:
      'QA Automation Engineer para nuevo proyecto, contratación por nómina en Colombia, proyecto de 6 meses, inglés básico. Buscan +3 años en QA/automatización, experiencia en pruebas de soluciones de AI, GenAI, LLMs o agentes de AI, Azure DevOps y CI/CD, evaluación de LLMs (hallucination, groundedness y calidad de respuestas), manejo de YAML/JSON. Postulación: contactar al reclutador vía LinkedIn (publicación #QAAutomation #GenAI #LLM #Colombia).',
    tags: ['qa automation', 'automation', 'ai', 'ia', 'llm', 'generative ai', 'azure devops', 'ci/cd', 'api testing'],
    salary: '',
    date: '2026-09-01',
  },
  {
    id: 'curated-co-hyg-analista-qa',
    source: 'Directo (HyG Consultores)',
    title: 'Analista de Requisitos y Calidad de Software (QA)',
    company: 'HyG Consultores',
    location: 'Medellín, Colombia',
    regionGuess: 'colombia',
    applyUrl: 'https://www.hyg.com.co',
    description:
      'HyG Consultores busca Analista de Requisitos y Calidad de Software (QA) con mínimo 1 año de experiencia, presencial en Medellín / Valle de Aburrá. Requisitos clave: metodologías ágiles, levantamiento de requisitos, diseño/ejecución de pruebas, Jira/Azure DevOps, SQL y Excel. Enviar hoja de vida a gestionhumana@hyg.com.co.',
    tags: ['qa', 'analista funcional', 'analista', 'testing', 'functional testing', 'test cases', 'jira', 'azure devops', 'sql', 'agile'],
    salary: '',
    date: '2026-09-01',
  },

  // ============ CHILE ============
  {
    id: 'curated-cl-randstad-qa-junior',
    source: 'Directo (Randstad Chile)',
    title: 'Analista QA Junior',
    company: 'Randstad',
    location: 'Santiago, Chile (Híbrido)',
    regionGuess: 'chile',
    applyUrl: 'https://www.randstad.cl',
    description:
      'Randstad Chile busca Analista QA Junior para empresa de soluciones tecnológicas de gestión humana. Modalidad híbrida en Las Condes (Santiago de Chile), contrato plazo fijo luego indefinido. Requisitos: titulado/a de Ingeniería en Informática o afines (0 a 1 año de experiencia), manejo de JavaScript, Python, SCRUM y RESTful, conocimientos en buenas prácticas de QA, diseño y automatización de pruebas. Enviar CV a mariana.herrera@randstad.cl con asunto "QA Analyst Junior".',
    tags: ['qa', 'analista qa', 'qa automation', 'testing', 'javascript', 'python', 'scrum', 'rest', 'test automation'],
    salary: '',
    date: '2026-09-01',
  },
];
